import { bootstrapApplication } from '@angular/platform-browser';
import {
  RouteReuseStrategy,
  provideRouter,
  withPreloading,
  PreloadAllModules,
} from '@angular/router';
import {
  IonicRouteStrategy,
  provideIonicAngular,
} from '@ionic/angular/standalone';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { HTTP_INTERCEPTORS } from '@angular/common/http';
import { AuthInterceptor } from './app/interceptors/auth.interceptor';

import { routes } from './app/app.routes';
import { AppComponent } from './app/app.component';

// Registrar todos los iconos globalmente
import { addIcons } from 'ionicons';
import {
  home,
  addCircle,
  arrowBack,
  arrowBackOutline,
  addOutline,
  list,
  statsChart,
  settings,
  logOut,
  person,
  banOutline,
  car,
  carSport,
  cube,
  people,
  logoMicrosoft,
  cameraOutline,
  camera,
  saveOutline,
  closeOutline,
  close,
  createOutline,
  downloadOutline,
  imageOutline,
  cloudUploadOutline,
  documentText,
  eyeOutline,
  eyeOffOutline,
  checkmarkCircleOutline,
  checkmarkOutline,
  checkmark,
  calendarOutline,
  personOutline,
  personCircleOutline,
  carOutline,
  cubeOutline,
  documentTextOutline,
  filterOutline,
  addCircleOutline,
  chevronBackOutline,
  chevronForwardOutline,
  add,
  refreshOutline,
  closeCircleOutline,
  documentAttachOutline,
  shareSocialOutline,
  shareOutline,
  trashOutline,
  businessOutline,
  business,
  informationCircleOutline,
  alertCircleOutline,
  pricetagOutline,
  carSportOutline,
  busOutline,
  gridOutline,
  colorPaletteOutline,
  construct,
  constructOutline,
  callOutline,
  mailOutline,
  cardOutline,
  fileTrayOutline,
  scaleOutline,
  arrowUpCircle,
  arrowDownCircle,
  trendingUpOutline,
  trendingDownOutline,
  personCircle,
  cloudUpload,
  shieldCheckmarkOutline,
  cloudDownloadOutline,
} from 'ionicons/icons';

addIcons({
  home,
  addCircle,
  arrowBack,
  arrowBackOutline,
  addOutline,
  list,
  statsChart,
  settings,
  logOut,
  person,
  banOutline,
  car,
  carSport,
  cube,
  people,
  logoMicrosoft,
  cameraOutline,
  camera,
  saveOutline,
  closeOutline,
  close,
  createOutline,
  downloadOutline,
  imageOutline,
  cloudUploadOutline,
  documentText,
  eyeOutline,
  eyeOffOutline,
  checkmarkCircleOutline,
  checkmarkOutline,
  checkmark,
  calendarOutline,
  personOutline,
  personCircleOutline,
  carOutline,
  cubeOutline,
  documentTextOutline,
  filterOutline,
  addCircleOutline,
  chevronBackOutline,
  chevronForwardOutline,
  add,
  refreshOutline,
  closeCircleOutline,
  documentAttachOutline,
  shareSocialOutline,
  shareOutline,
  trashOutline,
  businessOutline,
  business,
  informationCircleOutline,
  alertCircleOutline,
  pricetagOutline,
  carSportOutline,
  busOutline,
  gridOutline,
  colorPaletteOutline,
  construct,
  constructOutline,
  callOutline,
  mailOutline,
  cardOutline,
  fileTrayOutline,
  scaleOutline,
  arrowUpCircle,
  arrowDownCircle,
  trendingUpOutline,
  trendingDownOutline,
  personCircle,
  cloudUpload,
  shieldCheckmarkOutline,
  cloudDownloadOutline,
});

bootstrapApplication(AppComponent, {
  providers: [
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
    { provide: HTTP_INTERCEPTORS, useClass: AuthInterceptor, multi: true },
    provideIonicAngular(),
    provideRouter(routes, withPreloading(PreloadAllModules)),
    provideHttpClient(),
  ],
});
